<?php  if ( ! defined("BASEPATH")) exit("No direct script access allowed");
$config["protocol"]="smtp";
$config["smtp_host"]="ssl://mail.rhodonitestore.com";
$config["smtp_port"]="465";
$config["smtp_timeout"]="30";
$config["smtp_user"]="info@rhodonitestore.com";
$config["smtp_pass"]="lDX?KWVZgkDA";
$config["charset"]="utf-8";
$config["newline"]="\r\n";
$config["mailtype"]="html";
